export const config = {
    DEFAULT_COMPANY_NAME:'杭州链录科技有限公司',
    DEFAULT_SEAL_TYPE:'检测专用章',
    SEAL_COLOR:'red',
    DEFAULT_SEAL_WIDTH: 200,
    SEAL_TYPE_MAX_LENGTH:110,
    DEFAUTL_FONT_SIZE:17,
    START_ANGLE:210,
    END_ANGLE:-30
}